services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  lancamentoservice:
    build:
      context: ./services
      dockerfile: lancamento/Dockerfile
    container_name: lancamentoservice
    environment:
      - DB_CONNECTION=Host=postgres;Port=5432;Database=${POSTGRES_LANCAMENTOS_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_DEFAULT_PASS}
      - ASPNETCORE_ENVIRONMENT="Development"
    depends_on:
      - postgres
      - rabbitmq
      - redis
    ports:
      - "5001:80"

  consolidadorservice:
    build:
      context: ./services
      dockerfile: consolidador/Dockerfile
    container_name: consolidadorservice
    environment:
      - DB_CONNECTION=Host=postgres;Port=5432;Database=${POSTGRES_CONSOLIDADOR_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_DEFAULT_PASS}
      - REDIS_HOST=redis
      - ASPNETCORE_ENVIRONMENT="Development"
    depends_on:
      - postgres
      - rabbitmq
      - redis
      - lancamentoservice
    ports:
      - "5002:80"
  apigateway:
    build:
      context: ./gateways/portal.gateway
      dockerfile: Dockerfile
    container_name: apigateway
    ports:
      - "5000:80"
    depends_on:
      - lancamentoservice
      - consolidadorservice


volumes:
  postgres_data: